title = "Remote File Access API"

[server]
host = "127.0.0.1"
port = 5000
debug = true

[features]

[JWT]
JWT_SECRET_KEY = "super-secret-key-change-me"

[LOG]
NAME = "RemoteApp"
PATH = "log/app.log"
LEVEL = "DEBUG"

[DATABASE]
SQLALCHEMY_DATABASE_URI = "sqlite:///project.db"
MODEL_PATH = "app.models"

[SOCKETIO_SERVER.APP_CONFIG]
async_mode = "eventlet"

[SOCKETIO_SERVER.NAMESPACES]
