"""更新角色

Revision ID: 87f289b7e335
Revises: b6f541d696fd
Create Date: 2025-08-26 13:50:57.319732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f289b7e335'
down_revision: Union[str, Sequence[str], None] = 'b6f541d696fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('file_limit', sa.Integer(), nullable=True, comment='總檔案數量限制 (-1 為無限)'))
    op.add_column('roles', sa.Column('permanent_file_limit', sa.Integer(), nullable=True, comment='永久檔案數量限制 (-1 為無限)'))
    op.add_column('roles', sa.Column('file_lifetime_days', sa.Integer(), nullable=True, comment='檔案生命週期(天) (-1 為無限)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'file_lifetime_days')
    op.drop_column('roles', 'permanent_file_limit')
    op.drop_column('roles', 'file_limit')
    # ### end Alembic commands ###
