"""調整

Revision ID: a5c2a7fe095c
Revises: 60b238f23df8
Create Date: 2025-08-24 18:54:32.116599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c2a7fe095c'
down_revision: Union[str, Sequence[str], None] = '60b238f23df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_name', sa.String(length=100), nullable=False, comment='權限名稱，用於顯示'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('permission_name')

    # ### end Alembic commands ###
