"""更新角色 欄位改回必填

Revision ID: b15b76d96bc8
Revises: 87f289b7e335
Create Date: 2025-08-26 13:54:21.824790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15b76d96bc8'
down_revision: Union[str, Sequence[str], None] = '87f289b7e335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'file_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'permanent_file_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'file_lifetime_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'file_lifetime_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roles', 'permanent_file_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roles', 'file_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
